#' Suppress matching future warnings generated by function 'checkPackageUsage'.

#' @name suppressUsageWarnings
#' @param warnings  [class]
#' @param package  [choice]  NULL is ok.  Defaults to NULL
#' @return \code{suppressUsageWarnings}: NULL
#' @export
suppressUsageWarnings <- function(warnings, package = NULL) {
    # Suppress matching future warnings generated by checkPackageFns
    assert_class(warnings, class = "usage_warning")
    assert_choice(package, installed_packages(), null.ok = TRUE)
    if (is.null(package))
        package = sUtils::last(stringr::str_split(getwd(), "/")[[1]])
    path = glue("~/RUsageTests/{package}/suppress.csv")
    dir = glue("~/RUsageTests/{package}")
    if (file.exists(path)){
        fwrite(rbindlist(list(fread(path), warnings)), path)
        g_success("Usage warnings suppressed! suppressed warnings are stored in '{path}'")
        return(invisible(NULL))
    }
    if(!dir.exists('~/RUsageTests'))
        dir.create('~/RUsageTests')
    if (!dir.exists(dir))
        dir.create(dir)

    fwrite(warnings, path)
    g_success("Usage warnings suppressed! suppressed warnings are stored in '{path}'")
    return(invisible(NULL))
    # Returns: NULL
}
