#' Suppress matching future warnings generated by checkPackageFns.

#' @name suppressUsageWarnings
#' @param warnings  [class]
#' @param package  [choice]  NULL is ok.  Defaults to NULL
#' @return \code{suppressUsageWarnings}: NULL
#' @export
suppressUsageWarnings <- function(warnings, package = NULL) {
    # Suppress matching future warnings generated by checkPackageFns
    assert_class(warnings, class = "usage_warning")
    assert_choice(package, installed_packages(), null.ok = TRUE)
    if (is.null(package))
        package = sUlits::last(stringr::str_split(getwd(), "/")[[1]])
    path = glue("~/RUsageTests/{package}/suppress.rds")
    dir = glue("~/RUsageTests/{package}")
    if (file.exists(path)){
        saveRDS(unique(c(readRDS(path), warnings)), path)
        return(invisible(NULL))
    }
    if(!dir.exists('~/RUsageTests'))
        dir.create('~/RUsageTests')
    if (!dir.exists(dir))
        dir.create(dir)

    saveRDS(warnings, path)
    return(invisible(NULL))
    # Returns: NULL
}
